package POJOS;
// Generated Dec 11, 2016 12:59:44 AM by Hibernate Tools 4.3.1



/**
 * CardDetails generated by hbm2java
 */
public class CardDetails  implements java.io.Serializable {


     private Integer idcardDetails;
     private User user;
     private String cardNo;
     private String exp;
     private String sec;
     private String fname;
     private String lname;

    public CardDetails() {
    }

	
    public CardDetails(User user) {
        this.user = user;
    }
    public CardDetails(User user, String cardNo, String exp, String sec, String fname, String lname) {
       this.user = user;
       this.cardNo = cardNo;
       this.exp = exp;
       this.sec = sec;
       this.fname = fname;
       this.lname = lname;
    }
   
    public Integer getIdcardDetails() {
        return this.idcardDetails;
    }
    
    public void setIdcardDetails(Integer idcardDetails) {
        this.idcardDetails = idcardDetails;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getCardNo() {
        return this.cardNo;
    }
    
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo;
    }
    public String getExp() {
        return this.exp;
    }
    
    public void setExp(String exp) {
        this.exp = exp;
    }
    public String getSec() {
        return this.sec;
    }
    
    public void setSec(String sec) {
        this.sec = sec;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }




}


