package POJOS;
// Generated Oct 16, 2016 2:02:03 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cart generated by hbm2java
 */
public class Cart  implements java.io.Serializable {


     private Integer idcart;
     private Color color;
     private Item item;
     private Size size;
     private User user;
     private Double total;
     private Date dateTime;
     private Set<CartItem> cartItems = new HashSet<CartItem>(0);

    public Cart() {
    }

	
    public Cart(Color color, Item item, Size size, User user) {
        this.color = color;
        this.item = item;
        this.size = size;
        this.user = user;
    }
    public Cart(Color color, Item item, Size size, User user, Double total, Date dateTime, Set<CartItem> cartItems) {
       this.color = color;
       this.item = item;
       this.size = size;
       this.user = user;
       this.total = total;
       this.dateTime = dateTime;
       this.cartItems = cartItems;
    }
   
    public Integer getIdcart() {
        return this.idcart;
    }
    
    public void setIdcart(Integer idcart) {
        this.idcart = idcart;
    }
    public Color getColor() {
        return this.color;
    }
    
    public void setColor(Color color) {
        this.color = color;
    }
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }
    public Size getSize() {
        return this.size;
    }
    
    public void setSize(Size size) {
        this.size = size;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }
    public Date getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }
    public Set<CartItem> getCartItems() {
        return this.cartItems;
    }
    
    public void setCartItems(Set<CartItem> cartItems) {
        this.cartItems = cartItems;
    }




}


