package POJOS;
// Generated Oct 8, 2016 7:36:06 AM by Hibernate Tools 4.3.1



/**
 * Cart generated by hbm2java
 */
public class Cart  implements java.io.Serializable {


     private Integer idcart;
     private Color color;
     private Item item;
     private Size size;
     private User user;
     private Integer qty;

    public Cart() {
    }

	
    public Cart(Color color, Item item, Size size, User user) {
        this.color = color;
        this.item = item;
        this.size = size;
        this.user = user;
    }
    public Cart(Color color, Item item, Size size, User user, Integer qty) {
       this.color = color;
       this.item = item;
       this.size = size;
       this.user = user;
       this.qty = qty;
    }
   
    public Integer getIdcart() {
        return this.idcart;
    }
    
    public void setIdcart(Integer idcart) {
        this.idcart = idcart;
    }
    public Color getColor() {
        return this.color;
    }
    
    public void setColor(Color color) {
        this.color = color;
    }
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }
    public Size getSize() {
        return this.size;
    }
    
    public void setSize(Size size) {
        this.size = size;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }




}


