package POJOS;
// Generated 02-Jul-2016 15:04:48 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cat generated by hbm2java
 */
public class Cat  implements java.io.Serializable {


     private Integer idcat;
     private String catname;
     private Integer status;
     private Set subcats = new HashSet(0);

    public Cat() {
    }

    public Cat(String catname, Integer status, Set subcats) {
       this.catname = catname;
       this.status = status;
       this.subcats = subcats;
    }
   
    public Integer getIdcat() {
        return this.idcat;
    }
    
    public void setIdcat(Integer idcat) {
        this.idcat = idcat;
    }
    public String getCatname() {
        return this.catname;
    }
    
    public void setCatname(String catname) {
        this.catname = catname;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set getSubcats() {
        return this.subcats;
    }
    
    public void setSubcats(Set subcats) {
        this.subcats = subcats;
    }




}


