package POJOS;
// Generated May 7, 2016 1:07:55 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Country generated by hbm2java
 */
public class Country  implements java.io.Serializable {


     private int idcountry;
     private String name;
     private Set users = new HashSet(0);

    public Country() {
    }

	
    public Country(int idcountry) {
        this.idcountry = idcountry;
    }
    public Country(int idcountry, String name, Set users) {
       this.idcountry = idcountry;
       this.name = name;
       this.users = users;
    }
   
    public int getIdcountry() {
        return this.idcountry;
    }
    
    public void setIdcountry(int idcountry) {
        this.idcountry = idcountry;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


