package POJOS;
// Generated Sep 20, 2016 12:22:51 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Grn generated by hbm2java
 */
public class Grn  implements java.io.Serializable {


     private int grnid;
     private Item item;
     private Stock stock;
     private Supplier supplier;
     private User user;
     private Date deteTime;
     private Double cost;
     private Integer qty;
     private Double total;
     private Integer discount;
     private Double pay;
     private Double bal;
     private Integer status;

    public Grn() {
    }

	
    public Grn(int grnid, Item item, Stock stock, Supplier supplier, User user) {
        this.grnid = grnid;
        this.item = item;
        this.stock = stock;
        this.supplier = supplier;
        this.user = user;
    }
    public Grn(int grnid, Item item, Stock stock, Supplier supplier, User user, Date deteTime, Double cost, Integer qty, Double total, Integer discount, Double pay, Double bal, Integer status) {
       this.grnid = grnid;
       this.item = item;
       this.stock = stock;
       this.supplier = supplier;
       this.user = user;
       this.deteTime = deteTime;
       this.cost = cost;
       this.qty = qty;
       this.total = total;
       this.discount = discount;
       this.pay = pay;
       this.bal = bal;
       this.status = status;
    }
   
    public int getGrnid() {
        return this.grnid;
    }
    
    public void setGrnid(int grnid) {
        this.grnid = grnid;
    }
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }
    public Stock getStock() {
        return this.stock;
    }
    
    public void setStock(Stock stock) {
        this.stock = stock;
    }
    public Supplier getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(Supplier supplier) {
        this.supplier = supplier;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Date getDeteTime() {
        return this.deteTime;
    }
    
    public void setDeteTime(Date deteTime) {
        this.deteTime = deteTime;
    }
    public Double getCost() {
        return this.cost;
    }
    
    public void setCost(Double cost) {
        this.cost = cost;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }
    public Integer getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Integer discount) {
        this.discount = discount;
    }
    public Double getPay() {
        return this.pay;
    }
    
    public void setPay(Double pay) {
        this.pay = pay;
    }
    public Double getBal() {
        return this.bal;
    }
    
    public void setBal(Double bal) {
        this.bal = bal;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }




}


