package POJOS;
// Generated May 7, 2016 1:07:55 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Grn generated by hbm2java
 */
public class Grn  implements java.io.Serializable {


     private int grnid;
     private Supplier supplier;
     private User user;
     private String date;
     private String time;
     private String pmode;
     private Double total;
     private Double cash;
     private Double bal;
     private Integer status;
     private Set grnRegs = new HashSet(0);

    public Grn() {
    }

	
    public Grn(int grnid, Supplier supplier, User user) {
        this.grnid = grnid;
        this.supplier = supplier;
        this.user = user;
    }
    public Grn(int grnid, Supplier supplier, User user, String date, String time, String pmode, Double total, Double cash, Double bal, Integer status, Set grnRegs) {
       this.grnid = grnid;
       this.supplier = supplier;
       this.user = user;
       this.date = date;
       this.time = time;
       this.pmode = pmode;
       this.total = total;
       this.cash = cash;
       this.bal = bal;
       this.status = status;
       this.grnRegs = grnRegs;
    }
   
    public int getGrnid() {
        return this.grnid;
    }
    
    public void setGrnid(int grnid) {
        this.grnid = grnid;
    }
    public Supplier getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(Supplier supplier) {
        this.supplier = supplier;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public String getTime() {
        return this.time;
    }
    
    public void setTime(String time) {
        this.time = time;
    }
    public String getPmode() {
        return this.pmode;
    }
    
    public void setPmode(String pmode) {
        this.pmode = pmode;
    }
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }
    public Double getCash() {
        return this.cash;
    }
    
    public void setCash(Double cash) {
        this.cash = cash;
    }
    public Double getBal() {
        return this.bal;
    }
    
    public void setBal(Double bal) {
        this.bal = bal;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set getGrnRegs() {
        return this.grnRegs;
    }
    
    public void setGrnRegs(Set grnRegs) {
        this.grnRegs = grnRegs;
    }




}


