package POJOS;
// Generated Dec 13, 2016 9:42:23 AM by Hibernate Tools 4.3.1



/**
 * InvoiceItem generated by hbm2java
 */
public class InvoiceItem  implements java.io.Serializable {


     private Integer idinvoiceItem;
     private Invoice invoice;
     private Item item;
     private Stock stock;
     private Integer qty;
     private Double price;
     private Double total;

    public InvoiceItem() {
    }

	
    public InvoiceItem(Invoice invoice, Item item, Stock stock) {
        this.invoice = invoice;
        this.item = item;
        this.stock = stock;
    }
    public InvoiceItem(Invoice invoice, Item item, Stock stock, Integer qty, Double price, Double total) {
       this.invoice = invoice;
       this.item = item;
       this.stock = stock;
       this.qty = qty;
       this.price = price;
       this.total = total;
    }
   
    public Integer getIdinvoiceItem() {
        return this.idinvoiceItem;
    }
    
    public void setIdinvoiceItem(Integer idinvoiceItem) {
        this.idinvoiceItem = idinvoiceItem;
    }
    public Invoice getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }
    public Stock getStock() {
        return this.stock;
    }
    
    public void setStock(Stock stock) {
        this.stock = stock;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }




}


