package POJOS;
// Generated Dec 13, 2016 9:42:23 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Invoice generated by hbm2java
 */
public class Invoice  implements java.io.Serializable {


     private Integer idinvoice;
     private CardDetails cardDetails;
     private State stateByDelState;
     private State stateByStateIdstate;
     private User user;
     private String invoiceNo;
     private String billAddress;
     private String billCity;
     private String billZip;
     private Date date;
     private Date time;
     private Double total;
     private String delAddress;
     private String delCitiy;
     private String delZip;
     private Integer status;
     private Integer delivery;
     private Integer comp;
     private Set<InvoiceItem> invoiceItems = new HashSet<InvoiceItem>(0);

    public Invoice() {
    }

	
    public Invoice(CardDetails cardDetails, State stateByDelState, State stateByStateIdstate, User user) {
        this.cardDetails = cardDetails;
        this.stateByDelState = stateByDelState;
        this.stateByStateIdstate = stateByStateIdstate;
        this.user = user;
    }
    public Invoice(CardDetails cardDetails, State stateByDelState, State stateByStateIdstate, User user, String invoiceNo, String billAddress, String billCity, String billZip, Date date, Date time, Double total, String delAddress, String delCitiy, String delZip, Integer status, Integer delivery, Integer comp, Set<InvoiceItem> invoiceItems) {
       this.cardDetails = cardDetails;
       this.stateByDelState = stateByDelState;
       this.stateByStateIdstate = stateByStateIdstate;
       this.user = user;
       this.invoiceNo = invoiceNo;
       this.billAddress = billAddress;
       this.billCity = billCity;
       this.billZip = billZip;
       this.date = date;
       this.time = time;
       this.total = total;
       this.delAddress = delAddress;
       this.delCitiy = delCitiy;
       this.delZip = delZip;
       this.status = status;
       this.delivery = delivery;
       this.comp = comp;
       this.invoiceItems = invoiceItems;
    }
   
    public Integer getIdinvoice() {
        return this.idinvoice;
    }
    
    public void setIdinvoice(Integer idinvoice) {
        this.idinvoice = idinvoice;
    }
    public CardDetails getCardDetails() {
        return this.cardDetails;
    }
    
    public void setCardDetails(CardDetails cardDetails) {
        this.cardDetails = cardDetails;
    }
    public State getStateByDelState() {
        return this.stateByDelState;
    }
    
    public void setStateByDelState(State stateByDelState) {
        this.stateByDelState = stateByDelState;
    }
    public State getStateByStateIdstate() {
        return this.stateByStateIdstate;
    }
    
    public void setStateByStateIdstate(State stateByStateIdstate) {
        this.stateByStateIdstate = stateByStateIdstate;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getInvoiceNo() {
        return this.invoiceNo;
    }
    
    public void setInvoiceNo(String invoiceNo) {
        this.invoiceNo = invoiceNo;
    }
    public String getBillAddress() {
        return this.billAddress;
    }
    
    public void setBillAddress(String billAddress) {
        this.billAddress = billAddress;
    }
    public String getBillCity() {
        return this.billCity;
    }
    
    public void setBillCity(String billCity) {
        this.billCity = billCity;
    }
    public String getBillZip() {
        return this.billZip;
    }
    
    public void setBillZip(String billZip) {
        this.billZip = billZip;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }
    public String getDelAddress() {
        return this.delAddress;
    }
    
    public void setDelAddress(String delAddress) {
        this.delAddress = delAddress;
    }
    public String getDelCitiy() {
        return this.delCitiy;
    }
    
    public void setDelCitiy(String delCitiy) {
        this.delCitiy = delCitiy;
    }
    public String getDelZip() {
        return this.delZip;
    }
    
    public void setDelZip(String delZip) {
        this.delZip = delZip;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Integer getDelivery() {
        return this.delivery;
    }
    
    public void setDelivery(Integer delivery) {
        this.delivery = delivery;
    }
    public Integer getComp() {
        return this.comp;
    }
    
    public void setComp(Integer comp) {
        this.comp = comp;
    }
    public Set<InvoiceItem> getInvoiceItems() {
        return this.invoiceItems;
    }
    
    public void setInvoiceItems(Set<InvoiceItem> invoiceItems) {
        this.invoiceItems = invoiceItems;
    }




}


