package POJOS;
// Generated Dec 11, 2016 12:59:44 AM by Hibernate Tools 4.3.1



/**
 * InvoiceItem generated by hbm2java
 */
public class InvoiceItem  implements java.io.Serializable {


     private Integer idinvoiceItem;
     private Stock stock;
     private Integer qty;
     private Double price;
     private Double total;

    public InvoiceItem() {
    }

	
    public InvoiceItem(Stock stock) {
        this.stock = stock;
    }
    public InvoiceItem(Stock stock, Integer qty, Double price, Double total) {
       this.stock = stock;
       this.qty = qty;
       this.price = price;
       this.total = total;
    }
   
    public Integer getIdinvoiceItem() {
        return this.idinvoiceItem;
    }
    
    public void setIdinvoiceItem(Integer idinvoiceItem) {
        this.idinvoiceItem = idinvoiceItem;
    }
    public Stock getStock() {
        return this.stock;
    }
    
    public void setStock(Stock stock) {
        this.stock = stock;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }




}


