package POJOS;
// Generated Dec 11, 2016 12:59:44 AM by Hibernate Tools 4.3.1



/**
 * ItemPerPage generated by hbm2java
 */
public class ItemPerPage  implements java.io.Serializable {


     private Integer iditemPerPage;
     private User user;
     private Integer item;

    public ItemPerPage() {
    }

	
    public ItemPerPage(User user) {
        this.user = user;
    }
    public ItemPerPage(User user, Integer item) {
       this.user = user;
       this.item = item;
    }
   
    public Integer getIditemPerPage() {
        return this.iditemPerPage;
    }
    
    public void setIditemPerPage(Integer iditemPerPage) {
        this.iditemPerPage = iditemPerPage;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Integer getItem() {
        return this.item;
    }
    
    public void setItem(Integer item) {
        this.item = item;
    }




}


