package POJOS;
// Generated Dec 13, 2016 9:42:23 AM by Hibernate Tools 4.3.1



/**
 * ItemImage generated by hbm2java
 */
public class ItemImage  implements java.io.Serializable {


     private Integer iditemImage;
     private Item item;
     private String url;

    public ItemImage() {
    }

	
    public ItemImage(Item item) {
        this.item = item;
    }
    public ItemImage(Item item, String url) {
       this.item = item;
       this.url = url;
    }
   
    public Integer getIditemImage() {
        return this.iditemImage;
    }
    
    public void setIditemImage(Integer iditemImage) {
        this.iditemImage = iditemImage;
    }
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }




}


