package POJOS;
// Generated Dec 11, 2016 12:59:44 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Item generated by hbm2java
 */
public class Item  implements java.io.Serializable {


     private Integer iditem;
     private Subcat subcat;
     private String itemname;
     private Integer watching;
     private String description;
     private String url;
     private String delivary;
     private Integer status;
     private Set<Color> colors = new HashSet<Color>(0);
     private Set<CartItem> cartItems = new HashSet<CartItem>(0);
     private Set<TempGrnItem> tempGrnItems = new HashSet<TempGrnItem>(0);
     private Set<WatchList> watchLists = new HashSet<WatchList>(0);
     private Set<Size> sizes = new HashSet<Size>(0);
     private Set<GrnItem> grnItems = new HashSet<GrnItem>(0);
     private Set<Stock> stocks = new HashSet<Stock>(0);
     private Set<ItemImage> itemImages = new HashSet<ItemImage>(0);
     private Set<Question> questions = new HashSet<Question>(0);

    public Item() {
    }

	
    public Item(Subcat subcat) {
        this.subcat = subcat;
    }
    public Item(Subcat subcat, String itemname, Integer watching, String description, String url, String delivary, Integer status, Set<Color> colors, Set<CartItem> cartItems, Set<TempGrnItem> tempGrnItems, Set<WatchList> watchLists, Set<Size> sizes, Set<GrnItem> grnItems, Set<Stock> stocks, Set<ItemImage> itemImages, Set<Question> questions) {
       this.subcat = subcat;
       this.itemname = itemname;
       this.watching = watching;
       this.description = description;
       this.url = url;
       this.delivary = delivary;
       this.status = status;
       this.colors = colors;
       this.cartItems = cartItems;
       this.tempGrnItems = tempGrnItems;
       this.watchLists = watchLists;
       this.sizes = sizes;
       this.grnItems = grnItems;
       this.stocks = stocks;
       this.itemImages = itemImages;
       this.questions = questions;
    }
   
    public Integer getIditem() {
        return this.iditem;
    }
    
    public void setIditem(Integer iditem) {
        this.iditem = iditem;
    }
    public Subcat getSubcat() {
        return this.subcat;
    }
    
    public void setSubcat(Subcat subcat) {
        this.subcat = subcat;
    }
    public String getItemname() {
        return this.itemname;
    }
    
    public void setItemname(String itemname) {
        this.itemname = itemname;
    }
    public Integer getWatching() {
        return this.watching;
    }
    
    public void setWatching(Integer watching) {
        this.watching = watching;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getDelivary() {
        return this.delivary;
    }
    
    public void setDelivary(String delivary) {
        this.delivary = delivary;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set<Color> getColors() {
        return this.colors;
    }
    
    public void setColors(Set<Color> colors) {
        this.colors = colors;
    }
    public Set<CartItem> getCartItems() {
        return this.cartItems;
    }
    
    public void setCartItems(Set<CartItem> cartItems) {
        this.cartItems = cartItems;
    }
    public Set<TempGrnItem> getTempGrnItems() {
        return this.tempGrnItems;
    }
    
    public void setTempGrnItems(Set<TempGrnItem> tempGrnItems) {
        this.tempGrnItems = tempGrnItems;
    }
    public Set<WatchList> getWatchLists() {
        return this.watchLists;
    }
    
    public void setWatchLists(Set<WatchList> watchLists) {
        this.watchLists = watchLists;
    }
    public Set<Size> getSizes() {
        return this.sizes;
    }
    
    public void setSizes(Set<Size> sizes) {
        this.sizes = sizes;
    }
    public Set<GrnItem> getGrnItems() {
        return this.grnItems;
    }
    
    public void setGrnItems(Set<GrnItem> grnItems) {
        this.grnItems = grnItems;
    }
    public Set<Stock> getStocks() {
        return this.stocks;
    }
    
    public void setStocks(Set<Stock> stocks) {
        this.stocks = stocks;
    }
    public Set<ItemImage> getItemImages() {
        return this.itemImages;
    }
    
    public void setItemImages(Set<ItemImage> itemImages) {
        this.itemImages = itemImages;
    }
    public Set<Question> getQuestions() {
        return this.questions;
    }
    
    public void setQuestions(Set<Question> questions) {
        this.questions = questions;
    }




}


