package POJOS;
// Generated Sep 20, 2016 12:22:51 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * LoginReg generated by hbm2java
 */
public class LoginReg  implements java.io.Serializable {


     private Integer idloginReg;
     private Login login;
     private Date indateTime;
     private Date outdateTime;

    public LoginReg() {
    }

	
    public LoginReg(Login login) {
        this.login = login;
    }
    public LoginReg(Login login, Date indateTime, Date outdateTime) {
       this.login = login;
       this.indateTime = indateTime;
       this.outdateTime = outdateTime;
    }
   
    public Integer getIdloginReg() {
        return this.idloginReg;
    }
    
    public void setIdloginReg(Integer idloginReg) {
        this.idloginReg = idloginReg;
    }
    public Login getLogin() {
        return this.login;
    }
    
    public void setLogin(Login login) {
        this.login = login;
    }
    public Date getIndateTime() {
        return this.indateTime;
    }
    
    public void setIndateTime(Date indateTime) {
        this.indateTime = indateTime;
    }
    public Date getOutdateTime() {
        return this.outdateTime;
    }
    
    public void setOutdateTime(Date outdateTime) {
        this.outdateTime = outdateTime;
    }




}


