package POJOS;
// Generated Jun 21, 2016 7:38:20 PM by Hibernate Tools 4.3.1



/**
 * Message generated by hbm2java
 */
public class Message  implements java.io.Serializable {


     private Integer idmessage;
     private User user;
     private String message;
     private Integer newmes;
     private Integer notification;

    public Message() {
    }

	
    public Message(User user) {
        this.user = user;
    }
    public Message(User user, String message, Integer newmes, Integer notification) {
       this.user = user;
       this.message = message;
       this.newmes = newmes;
       this.notification = notification;
    }
   
    public Integer getIdmessage() {
        return this.idmessage;
    }
    
    public void setIdmessage(Integer idmessage) {
        this.idmessage = idmessage;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }
    public Integer getNewmes() {
        return this.newmes;
    }
    
    public void setNewmes(Integer newmes) {
        this.newmes = newmes;
    }
    public Integer getNotification() {
        return this.notification;
    }
    
    public void setNotification(Integer notification) {
        this.notification = notification;
    }




}


