package POJOS;
// Generated Dec 13, 2016 9:42:23 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Message generated by hbm2java
 */
public class Message  implements java.io.Serializable {


     private Integer idmessage;
     private User userByMfrom;
     private User userByMto;
     private Utype utype;
     private String message;
     private Integer newmes;
     private Integer notification;
     private Date date;
     private Date time;

    public Message() {
    }

	
    public Message(User userByMfrom, User userByMto, Utype utype) {
        this.userByMfrom = userByMfrom;
        this.userByMto = userByMto;
        this.utype = utype;
    }
    public Message(User userByMfrom, User userByMto, Utype utype, String message, Integer newmes, Integer notification, Date date, Date time) {
       this.userByMfrom = userByMfrom;
       this.userByMto = userByMto;
       this.utype = utype;
       this.message = message;
       this.newmes = newmes;
       this.notification = notification;
       this.date = date;
       this.time = time;
    }
   
    public Integer getIdmessage() {
        return this.idmessage;
    }
    
    public void setIdmessage(Integer idmessage) {
        this.idmessage = idmessage;
    }
    public User getUserByMfrom() {
        return this.userByMfrom;
    }
    
    public void setUserByMfrom(User userByMfrom) {
        this.userByMfrom = userByMfrom;
    }
    public User getUserByMto() {
        return this.userByMto;
    }
    
    public void setUserByMto(User userByMto) {
        this.userByMto = userByMto;
    }
    public Utype getUtype() {
        return this.utype;
    }
    
    public void setUtype(Utype utype) {
        this.utype = utype;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }
    public Integer getNewmes() {
        return this.newmes;
    }
    
    public void setNewmes(Integer newmes) {
        this.newmes = newmes;
    }
    public Integer getNotification() {
        return this.notification;
    }
    
    public void setNotification(Integer notification) {
        this.notification = notification;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }




}


