package POJOS;
// Generated Oct 8, 2016 7:36:06 AM by Hibernate Tools 4.3.1



/**
 * Message generated by hbm2java
 */
public class Message  implements java.io.Serializable {


     private Integer idmessage;
     private User userByCustomer;
     private User userByAnita;
     private String message;
     private Integer newmes;
     private Integer notification;

    public Message() {
    }

	
    public Message(User userByCustomer, User userByAnita) {
        this.userByCustomer = userByCustomer;
        this.userByAnita = userByAnita;
    }
    public Message(User userByCustomer, User userByAnita, String message, Integer newmes, Integer notification) {
       this.userByCustomer = userByCustomer;
       this.userByAnita = userByAnita;
       this.message = message;
       this.newmes = newmes;
       this.notification = notification;
    }
   
    public Integer getIdmessage() {
        return this.idmessage;
    }
    
    public void setIdmessage(Integer idmessage) {
        this.idmessage = idmessage;
    }
    public User getUserByCustomer() {
        return this.userByCustomer;
    }
    
    public void setUserByCustomer(User userByCustomer) {
        this.userByCustomer = userByCustomer;
    }
    public User getUserByAnita() {
        return this.userByAnita;
    }
    
    public void setUserByAnita(User userByAnita) {
        this.userByAnita = userByAnita;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }
    public Integer getNewmes() {
        return this.newmes;
    }
    
    public void setNewmes(Integer newmes) {
        this.newmes = newmes;
    }
    public Integer getNotification() {
        return this.notification;
    }
    
    public void setNotification(Integer notification) {
        this.notification = notification;
    }




}


