package POJOS;
// Generated Nov 29, 2016 12:42:00 PM by Hibernate Tools 4.3.1



/**
 * OnlineUsers generated by hbm2java
 */
public class OnlineUsers  implements java.io.Serializable {


     private Integer idonlineUsers;
     private User user;

    public OnlineUsers() {
    }

    public OnlineUsers(User user) {
       this.user = user;
    }
   
    public Integer getIdonlineUsers() {
        return this.idonlineUsers;
    }
    
    public void setIdonlineUsers(Integer idonlineUsers) {
        this.idonlineUsers = idonlineUsers;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }




}


