package POJOS;
// Generated Nov 6, 2016 9:42:09 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pages generated by hbm2java
 */
public class Pages  implements java.io.Serializable {


     private Integer idpages;
     private String pageName;
     private Set<PagesHasUtype> pagesHasUtypes = new HashSet<PagesHasUtype>(0);

    public Pages() {
    }

    public Pages(String pageName, Set<PagesHasUtype> pagesHasUtypes) {
       this.pageName = pageName;
       this.pagesHasUtypes = pagesHasUtypes;
    }
   
    public Integer getIdpages() {
        return this.idpages;
    }
    
    public void setIdpages(Integer idpages) {
        this.idpages = idpages;
    }
    public String getPageName() {
        return this.pageName;
    }
    
    public void setPageName(String pageName) {
        this.pageName = pageName;
    }
    public Set<PagesHasUtype> getPagesHasUtypes() {
        return this.pagesHasUtypes;
    }
    
    public void setPagesHasUtypes(Set<PagesHasUtype> pagesHasUtypes) {
        this.pagesHasUtypes = pagesHasUtypes;
    }




}


