package POJOS;
// Generated Nov 29, 2016 12:42:00 PM by Hibernate Tools 4.3.1



/**
 * Question generated by hbm2java
 */
public class Question  implements java.io.Serializable {


     private Integer idquestion;
     private Item item;
     private User user;
     private String question;

    public Question() {
    }

	
    public Question(Item item, User user) {
        this.item = item;
        this.user = user;
    }
    public Question(Item item, User user, String question) {
       this.item = item;
       this.user = user;
       this.question = question;
    }
   
    public Integer getIdquestion() {
        return this.idquestion;
    }
    
    public void setIdquestion(Integer idquestion) {
        this.idquestion = idquestion;
    }
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getQuestion() {
        return this.question;
    }
    
    public void setQuestion(String question) {
        this.question = question;
    }




}


