package POJOS;
// Generated 01-Jul-2016 05:52:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Register generated by hbm2java
 */
public class Register  implements java.io.Serializable {


     private Integer idregister;
     private String email;
     private String fname;
     private String lname;
     private String password;
     private Integer mobile;
     private Set users = new HashSet(0);

    public Register() {
    }

    public Register(String email, String fname, String lname, String password, Integer mobile, Set users) {
       this.email = email;
       this.fname = fname;
       this.lname = lname;
       this.password = password;
       this.mobile = mobile;
       this.users = users;
    }
   
    public Integer getIdregister() {
        return this.idregister;
    }
    
    public void setIdregister(Integer idregister) {
        this.idregister = idregister;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Integer getMobile() {
        return this.mobile;
    }
    
    public void setMobile(Integer mobile) {
        this.mobile = mobile;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


