package POJOS;
// Generated Sep 20, 2016 12:22:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Size generated by hbm2java
 */
public class Size  implements java.io.Serializable {


     private Integer idsize;
     private String size;
     private Set<Cart> carts = new HashSet<Cart>(0);
     private Set<Item> items = new HashSet<Item>(0);

    public Size() {
    }

    public Size(String size, Set<Cart> carts, Set<Item> items) {
       this.size = size;
       this.carts = carts;
       this.items = items;
    }
   
    public Integer getIdsize() {
        return this.idsize;
    }
    
    public void setIdsize(Integer idsize) {
        this.idsize = idsize;
    }
    public String getSize() {
        return this.size;
    }
    
    public void setSize(String size) {
        this.size = size;
    }
    public Set<Cart> getCarts() {
        return this.carts;
    }
    
    public void setCarts(Set<Cart> carts) {
        this.carts = carts;
    }
    public Set<Item> getItems() {
        return this.items;
    }
    
    public void setItems(Set<Item> items) {
        this.items = items;
    }




}


