package POJOS;
// Generated Sep 25, 2016 9:30:20 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Size generated by hbm2java
 */
public class Size  implements java.io.Serializable {


     private Integer idsize;
     private String size;
     private Set carts = new HashSet(0);
     private Set items = new HashSet(0);

    public Size() {
    }

    public Size(String size, Set carts, Set items) {
       this.size = size;
       this.carts = carts;
       this.items = items;
    }
   
    public Integer getIdsize() {
        return this.idsize;
    }
    
    public void setIdsize(Integer idsize) {
        this.idsize = idsize;
    }
    public String getSize() {
        return this.size;
    }
    
    public void setSize(String size) {
        this.size = size;
    }
    public Set getCarts() {
        return this.carts;
    }
    
    public void setCarts(Set carts) {
        this.carts = carts;
    }
    public Set getItems() {
        return this.items;
    }
    
    public void setItems(Set items) {
        this.items = items;
    }




}


