package POJOS;
// Generated Oct 8, 2016 7:36:06 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * State generated by hbm2java
 */
public class State  implements java.io.Serializable {


     private Integer idstate;
     private String state;
     private Double deliveryPrice;
     private Set<Supplier> suppliers = new HashSet<Supplier>(0);
     private Set<Addres> addreses = new HashSet<Addres>(0);

    public State() {
    }

    public State(String state, Double deliveryPrice, Set<Supplier> suppliers, Set<Addres> addreses) {
       this.state = state;
       this.deliveryPrice = deliveryPrice;
       this.suppliers = suppliers;
       this.addreses = addreses;
    }
   
    public Integer getIdstate() {
        return this.idstate;
    }
    
    public void setIdstate(Integer idstate) {
        this.idstate = idstate;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public Double getDeliveryPrice() {
        return this.deliveryPrice;
    }
    
    public void setDeliveryPrice(Double deliveryPrice) {
        this.deliveryPrice = deliveryPrice;
    }
    public Set<Supplier> getSuppliers() {
        return this.suppliers;
    }
    
    public void setSuppliers(Set<Supplier> suppliers) {
        this.suppliers = suppliers;
    }
    public Set<Addres> getAddreses() {
        return this.addreses;
    }
    
    public void setAddreses(Set<Addres> addreses) {
        this.addreses = addreses;
    }




}


