package POJOS;
// Generated Dec 13, 2016 9:42:23 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * State generated by hbm2java
 */
public class State  implements java.io.Serializable {


     private Integer idstate;
     private String state;
     private Double deliveryPrice;
     private Integer day;
     private Set<Invoice> invoicesForDelState = new HashSet<Invoice>(0);
     private Set<Invoice> invoicesForStateIdstate = new HashSet<Invoice>(0);
     private Set<Supplier> suppliers = new HashSet<Supplier>(0);
     private Set<Addres> addreses = new HashSet<Addres>(0);

    public State() {
    }

    public State(String state, Double deliveryPrice, Integer day, Set<Invoice> invoicesForDelState, Set<Invoice> invoicesForStateIdstate, Set<Supplier> suppliers, Set<Addres> addreses) {
       this.state = state;
       this.deliveryPrice = deliveryPrice;
       this.day = day;
       this.invoicesForDelState = invoicesForDelState;
       this.invoicesForStateIdstate = invoicesForStateIdstate;
       this.suppliers = suppliers;
       this.addreses = addreses;
    }
   
    public Integer getIdstate() {
        return this.idstate;
    }
    
    public void setIdstate(Integer idstate) {
        this.idstate = idstate;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public Double getDeliveryPrice() {
        return this.deliveryPrice;
    }
    
    public void setDeliveryPrice(Double deliveryPrice) {
        this.deliveryPrice = deliveryPrice;
    }
    public Integer getDay() {
        return this.day;
    }
    
    public void setDay(Integer day) {
        this.day = day;
    }
    public Set<Invoice> getInvoicesForDelState() {
        return this.invoicesForDelState;
    }
    
    public void setInvoicesForDelState(Set<Invoice> invoicesForDelState) {
        this.invoicesForDelState = invoicesForDelState;
    }
    public Set<Invoice> getInvoicesForStateIdstate() {
        return this.invoicesForStateIdstate;
    }
    
    public void setInvoicesForStateIdstate(Set<Invoice> invoicesForStateIdstate) {
        this.invoicesForStateIdstate = invoicesForStateIdstate;
    }
    public Set<Supplier> getSuppliers() {
        return this.suppliers;
    }
    
    public void setSuppliers(Set<Supplier> suppliers) {
        this.suppliers = suppliers;
    }
    public Set<Addres> getAddreses() {
        return this.addreses;
    }
    
    public void setAddreses(Set<Addres> addreses) {
        this.addreses = addreses;
    }




}


