package POJOS;
// Generated Dec 11, 2016 12:59:44 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Supplier generated by hbm2java
 */
public class Supplier  implements java.io.Serializable {


     private Integer idsupplier;
     private State state;
     private String fname;
     private String mname;
     private String lname;
     private String cname;
     private String contact1;
     private String contact2;
     private String email;
     private String address1;
     private String address2;
     private String address3;
     private Integer status;
     private Set<Grn> grns = new HashSet<Grn>(0);

    public Supplier() {
    }

	
    public Supplier(State state) {
        this.state = state;
    }
    public Supplier(State state, String fname, String mname, String lname, String cname, String contact1, String contact2, String email, String address1, String address2, String address3, Integer status, Set<Grn> grns) {
       this.state = state;
       this.fname = fname;
       this.mname = mname;
       this.lname = lname;
       this.cname = cname;
       this.contact1 = contact1;
       this.contact2 = contact2;
       this.email = email;
       this.address1 = address1;
       this.address2 = address2;
       this.address3 = address3;
       this.status = status;
       this.grns = grns;
    }
   
    public Integer getIdsupplier() {
        return this.idsupplier;
    }
    
    public void setIdsupplier(Integer idsupplier) {
        this.idsupplier = idsupplier;
    }
    public State getState() {
        return this.state;
    }
    
    public void setState(State state) {
        this.state = state;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getMname() {
        return this.mname;
    }
    
    public void setMname(String mname) {
        this.mname = mname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getCname() {
        return this.cname;
    }
    
    public void setCname(String cname) {
        this.cname = cname;
    }
    public String getContact1() {
        return this.contact1;
    }
    
    public void setContact1(String contact1) {
        this.contact1 = contact1;
    }
    public String getContact2() {
        return this.contact2;
    }
    
    public void setContact2(String contact2) {
        this.contact2 = contact2;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAddress1() {
        return this.address1;
    }
    
    public void setAddress1(String address1) {
        this.address1 = address1;
    }
    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }
    public String getAddress3() {
        return this.address3;
    }
    
    public void setAddress3(String address3) {
        this.address3 = address3;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set<Grn> getGrns() {
        return this.grns;
    }
    
    public void setGrns(Set<Grn> grns) {
        this.grns = grns;
    }




}


