package POJOS;
// Generated Oct 31, 2016 7:52:56 AM by Hibernate Tools 4.3.1



/**
 * TempSize generated by hbm2java
 */
public class TempSize  implements java.io.Serializable {


     private Integer idtempSize;
     private String size;

    public TempSize() {
    }

    public TempSize(String size) {
       this.size = size;
    }
   
    public Integer getIdtempSize() {
        return this.idtempSize;
    }
    
    public void setIdtempSize(Integer idtempSize) {
        this.idtempSize = idtempSize;
    }
    public String getSize() {
        return this.size;
    }
    
    public void setSize(String size) {
        this.size = size;
    }




}


