package POJOS;
// Generated Sep 20, 2016 12:22:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer iduser;
     private Utype utype;
     private String nic;
     private String fname;
     private String mname;
     private String lname;
     private String mobile;
     private String img;
     private Integer status;
     private Set<Cart> carts = new HashSet<Cart>(0);
     private Set<Addres> addreses = new HashSet<Addres>(0);
     private Set<Login> logins = new HashSet<Login>(0);
     private Set<WatchList> watchLists = new HashSet<WatchList>(0);
     private Set<Grn> grns = new HashSet<Grn>(0);
     private Set<Message> messagesForCustomer = new HashSet<Message>(0);
     private Set<Message> messagesForAnita = new HashSet<Message>(0);

    public User() {
    }

	
    public User(Utype utype) {
        this.utype = utype;
    }
    public User(Utype utype, String nic, String fname, String mname, String lname, String mobile, String img, Integer status, Set<Cart> carts, Set<Addres> addreses, Set<Login> logins, Set<WatchList> watchLists, Set<Grn> grns, Set<Message> messagesForCustomer, Set<Message> messagesForAnita) {
       this.utype = utype;
       this.nic = nic;
       this.fname = fname;
       this.mname = mname;
       this.lname = lname;
       this.mobile = mobile;
       this.img = img;
       this.status = status;
       this.carts = carts;
       this.addreses = addreses;
       this.logins = logins;
       this.watchLists = watchLists;
       this.grns = grns;
       this.messagesForCustomer = messagesForCustomer;
       this.messagesForAnita = messagesForAnita;
    }
   
    public Integer getIduser() {
        return this.iduser;
    }
    
    public void setIduser(Integer iduser) {
        this.iduser = iduser;
    }
    public Utype getUtype() {
        return this.utype;
    }
    
    public void setUtype(Utype utype) {
        this.utype = utype;
    }
    public String getNic() {
        return this.nic;
    }
    
    public void setNic(String nic) {
        this.nic = nic;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getMname() {
        return this.mname;
    }
    
    public void setMname(String mname) {
        this.mname = mname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getImg() {
        return this.img;
    }
    
    public void setImg(String img) {
        this.img = img;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set<Cart> getCarts() {
        return this.carts;
    }
    
    public void setCarts(Set<Cart> carts) {
        this.carts = carts;
    }
    public Set<Addres> getAddreses() {
        return this.addreses;
    }
    
    public void setAddreses(Set<Addres> addreses) {
        this.addreses = addreses;
    }
    public Set<Login> getLogins() {
        return this.logins;
    }
    
    public void setLogins(Set<Login> logins) {
        this.logins = logins;
    }
    public Set<WatchList> getWatchLists() {
        return this.watchLists;
    }
    
    public void setWatchLists(Set<WatchList> watchLists) {
        this.watchLists = watchLists;
    }
    public Set<Grn> getGrns() {
        return this.grns;
    }
    
    public void setGrns(Set<Grn> grns) {
        this.grns = grns;
    }
    public Set<Message> getMessagesForCustomer() {
        return this.messagesForCustomer;
    }
    
    public void setMessagesForCustomer(Set<Message> messagesForCustomer) {
        this.messagesForCustomer = messagesForCustomer;
    }
    public Set<Message> getMessagesForAnita() {
        return this.messagesForAnita;
    }
    
    public void setMessagesForAnita(Set<Message> messagesForAnita) {
        this.messagesForAnita = messagesForAnita;
    }




}


