package POJOS;
// Generated Sep 25, 2016 9:30:20 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer iduser;
     private Utype utype;
     private String nic;
     private String fname;
     private String mname;
     private String lname;
     private String mobile;
     private String mobile2;
     private String img;
     private Integer status;
     private Set carts = new HashSet(0);
     private Set addreses = new HashSet(0);
     private Set logins = new HashSet(0);
     private Set watchLists = new HashSet(0);
     private Set messagesForCustomer = new HashSet(0);
     private Set messagesForAnita = new HashSet(0);

    public User() {
    }

	
    public User(Utype utype) {
        this.utype = utype;
    }
    public User(Utype utype, String nic, String fname, String mname, String lname, String mobile, String mobile2, String img, Integer status, Set carts, Set addreses, Set logins, Set watchLists, Set messagesForCustomer, Set messagesForAnita) {
       this.utype = utype;
       this.nic = nic;
       this.fname = fname;
       this.mname = mname;
       this.lname = lname;
       this.mobile = mobile;
       this.mobile2 = mobile2;
       this.img = img;
       this.status = status;
       this.carts = carts;
       this.addreses = addreses;
       this.logins = logins;
       this.watchLists = watchLists;
       this.messagesForCustomer = messagesForCustomer;
       this.messagesForAnita = messagesForAnita;
    }
   
    public Integer getIduser() {
        return this.iduser;
    }
    
    public void setIduser(Integer iduser) {
        this.iduser = iduser;
    }
    public Utype getUtype() {
        return this.utype;
    }
    
    public void setUtype(Utype utype) {
        this.utype = utype;
    }
    public String getNic() {
        return this.nic;
    }
    
    public void setNic(String nic) {
        this.nic = nic;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getMname() {
        return this.mname;
    }
    
    public void setMname(String mname) {
        this.mname = mname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getMobile2() {
        return this.mobile2;
    }
    
    public void setMobile2(String mobile2) {
        this.mobile2 = mobile2;
    }
    public String getImg() {
        return this.img;
    }
    
    public void setImg(String img) {
        this.img = img;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set getCarts() {
        return this.carts;
    }
    
    public void setCarts(Set carts) {
        this.carts = carts;
    }
    public Set getAddreses() {
        return this.addreses;
    }
    
    public void setAddreses(Set addreses) {
        this.addreses = addreses;
    }
    public Set getLogins() {
        return this.logins;
    }
    
    public void setLogins(Set logins) {
        this.logins = logins;
    }
    public Set getWatchLists() {
        return this.watchLists;
    }
    
    public void setWatchLists(Set watchLists) {
        this.watchLists = watchLists;
    }
    public Set getMessagesForCustomer() {
        return this.messagesForCustomer;
    }
    
    public void setMessagesForCustomer(Set messagesForCustomer) {
        this.messagesForCustomer = messagesForCustomer;
    }
    public Set getMessagesForAnita() {
        return this.messagesForAnita;
    }
    
    public void setMessagesForAnita(Set messagesForAnita) {
        this.messagesForAnita = messagesForAnita;
    }




}


