package POJOS;
// Generated 02-Jul-2016 15:04:48 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer iduser;
     private Utype utype;
     private String fname;
     private String mname;
     private String lname;
     private String mobile;
     private String img;
     private Integer status;
     private Set grns = new HashSet(0);
     private Set messages = new HashSet(0);
     private Set watchLists = new HashSet(0);
     private Set logins = new HashSet(0);
     private Set addreses = new HashSet(0);

    public User() {
    }

	
    public User(Utype utype) {
        this.utype = utype;
    }
    public User(Utype utype, String fname, String mname, String lname, String mobile, String img, Integer status, Set grns, Set messages, Set watchLists, Set logins, Set addreses) {
       this.utype = utype;
       this.fname = fname;
       this.mname = mname;
       this.lname = lname;
       this.mobile = mobile;
       this.img = img;
       this.status = status;
       this.grns = grns;
       this.messages = messages;
       this.watchLists = watchLists;
       this.logins = logins;
       this.addreses = addreses;
    }
   
    public Integer getIduser() {
        return this.iduser;
    }
    
    public void setIduser(Integer iduser) {
        this.iduser = iduser;
    }
    public Utype getUtype() {
        return this.utype;
    }
    
    public void setUtype(Utype utype) {
        this.utype = utype;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getMname() {
        return this.mname;
    }
    
    public void setMname(String mname) {
        this.mname = mname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getImg() {
        return this.img;
    }
    
    public void setImg(String img) {
        this.img = img;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set getGrns() {
        return this.grns;
    }
    
    public void setGrns(Set grns) {
        this.grns = grns;
    }
    public Set getMessages() {
        return this.messages;
    }
    
    public void setMessages(Set messages) {
        this.messages = messages;
    }
    public Set getWatchLists() {
        return this.watchLists;
    }
    
    public void setWatchLists(Set watchLists) {
        this.watchLists = watchLists;
    }
    public Set getLogins() {
        return this.logins;
    }
    
    public void setLogins(Set logins) {
        this.logins = logins;
    }
    public Set getAddreses() {
        return this.addreses;
    }
    
    public void setAddreses(Set addreses) {
        this.addreses = addreses;
    }




}


