package POJOS;
// Generated Nov 6, 2016 9:42:09 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Utype generated by hbm2java
 */
public class Utype  implements java.io.Serializable {


     private Integer idutype;
     private String utype;
     private Set<Message> messages = new HashSet<Message>(0);
     private Set<User> users = new HashSet<User>(0);
     private Set<PagesHasUtype> pagesHasUtypes = new HashSet<PagesHasUtype>(0);

    public Utype() {
    }

    public Utype(String utype, Set<Message> messages, Set<User> users, Set<PagesHasUtype> pagesHasUtypes) {
       this.utype = utype;
       this.messages = messages;
       this.users = users;
       this.pagesHasUtypes = pagesHasUtypes;
    }
   
    public Integer getIdutype() {
        return this.idutype;
    }
    
    public void setIdutype(Integer idutype) {
        this.idutype = idutype;
    }
    public String getUtype() {
        return this.utype;
    }
    
    public void setUtype(String utype) {
        this.utype = utype;
    }
    public Set<Message> getMessages() {
        return this.messages;
    }
    
    public void setMessages(Set<Message> messages) {
        this.messages = messages;
    }
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }
    public Set<PagesHasUtype> getPagesHasUtypes() {
        return this.pagesHasUtypes;
    }
    
    public void setPagesHasUtypes(Set<PagesHasUtype> pagesHasUtypes) {
        this.pagesHasUtypes = pagesHasUtypes;
    }




}


